#NAME: Destin Raymundo, Deven Agrawal
#EMAIL: draym001@ucla.edu, devenargrawal.810@gmail.com
#ID: 904852807, 104646996

default: lab3b
	chmod 777 lab3b

dist:
	tar -czvf lab3b-904852807.tar.gz lab3b README Makefile

clean:
	rm -f *.tar.gz
