#NAME: Destin Raymundo, Deven Agrawal
#EMAIL: draym001@ucla.edu, devenargrawal.810@gmail.com
#ID: 904852807, 104646996

default: lab3b.py
	chmod 777 lab3b.py
do:
	python lab3b.py trivial.csv
file:
	python lab3b.py trivial.csv > newfile
